import { Prompt, Category } from './types';

export const CATEGORIES: Category[] = ["Marketing", "Development", "Art", "Writing", "Business"];

export const PROMPTS: Prompt[] = [
  {
    id: 1,
    title: "E-commerce Product Description Generator",
    description: "Generates persuasive and SEO-friendly product descriptions for any e-commerce item.",
    promptText: "Generate a compelling, SEO-friendly product description for the following item: [Product Name]. Key features include: [Feature 1], [Feature 2], [Feature 3]. The target audience is [Target Audience]. The description should be approximately 150 words and have a [Tone of Voice] tone.",
    model: "Gemini",
    author: "MarketingMaster",
    price: 9.99,
    rating: 4.8,
    category: "Marketing",
    tags: ["e-commerce", "seo", "copywriting"],
    exampleOutput: "Introducing the new AeroBlend Pro, the ultimate portable blender for health enthusiasts on the go! Featuring a powerful motor, stainless steel blades, and a rechargeable USB battery, this blender makes silky-smooth smoothies in seconds. Perfect for busy professionals and fitness lovers. Get yours today and blend your way to a healthier lifestyle!",
    createdAt: "2024-05-20T10:00:00Z",
  },
  {
    id: 2,
    title: "React Component Boilerplate Creator",
    description: "Quickly generates boilerplate code for a new React functional component with TypeScript and Tailwind CSS.",
    promptText: "Create the boilerplate code for a React functional component named '[ComponentName]'. It should use TypeScript for props interface named '[ComponentName]Props'. The component should accept the following props: [Prop definitions, e.g., 'title: string, count: number']. The component should be styled with Tailwind CSS and return a simple div containing the props.",
    model: "Gemini",
    author: "CodeWizard",
    price: 14.99,
    rating: 4.9,
    category: "Development",
    tags: ["react", "typescript", "frontend"],
    exampleOutput: "interface MyButtonProps {\n  text: string;\n  onClick: () => void;\n}\n\nconst MyButton: React.FC<MyButtonProps> = ({ text, onClick }) => {\n  return (\n    <button onClick={onClick} className='bg-blue-500 text-white p-2 rounded'>\n      {text}\n    </button>\n  );\n}; \n\nexport default MyButton;",
    createdAt: "2024-05-21T11:00:00Z",
  },
  {
    id: 3,
    title: "Fantasy Character Concept Art",
    description: "Creates visually stunning and imaginative concept art prompts for fantasy characters.",
    promptText: "Generate a detailed concept art prompt for a [Character Class], [Character Race]. The character should have [Specific Feature 1] and [Specific Feature 2], wearing [Type of Armor/Clothing]. The setting is a [Environment] with [Lighting Style] lighting. The art style should be hyper-realistic, fantasy, epic, detailed, trending on ArtStation.",
    model: "Midjourney",
    author: "ArtisticAI",
    price: 7.50,
    rating: 4.7,
    category: "Art",
    tags: ["concept art", "character design", "fantasy"],
    exampleOutput: "A hyper-realistic, epic fantasy concept art of an Elven rogue assassin. The character has glowing silver eyes and intricate tattoos, wearing dark leather armor with a hooded cloak. The setting is a moonlit, ancient forest with dramatic, cinematic lighting. Trending on ArtStation.",
    createdAt: "2024-05-19T09:00:00Z",
  },
  {
    id: 4,
    title: "Blog Post Outline Generator",
    description: "Structures a comprehensive and engaging blog post outline on any given topic.",
    promptText: "Create a detailed blog post outline for the topic: '[Blog Post Topic]'. The outline should include a catchy title, a brief introduction, at least 5 main sections with 2-3 bullet points under each, and a concluding paragraph. The target audience is [Target Audience].",
    model: "ChatGPT",
    author: "ContentCreator",
    price: 5.99,
    rating: 4.6,
    category: "Writing",
    tags: ["blogging", "content", "structure"],
    exampleOutput: "Title: 10 Time-Management Hacks for Remote Workers\nIntro: The challenges and importance of managing time while working from home.\n1. The Pomodoro Technique\n   - What it is\n   - How to implement\n2. ... (and so on)",
    createdAt: "2024-05-22T14:30:00Z",
  },
  {
    id: 5,
    title: "Business SWOT Analysis",
    description: "Generates a detailed SWOT (Strengths, Weaknesses, Opportunities, Threats) analysis for a business idea.",
    promptText: "Perform a detailed SWOT analysis for a business that [Business Description]. The business is in the [Industry] industry. Consider market trends, competition, and internal factors. Present the output in four distinct sections: Strengths, Weaknesses, Opportunities, and Threats.",
    model: "Gemini",
    author: "StrategyBot",
    price: 19.99,
    rating: 4.9,
    category: "Business",
    tags: ["strategy", "analysis", "startup"],
    exampleOutput: "For a local artisanal coffee shop:\nStrengths: High-quality, unique product; Strong community connection; Prime location.\nWeaknesses: Higher price point; Limited seating; Brand recognition.\nOpportunities: Catering services; Loyalty programs; Hosting local events.\nThreats: Competition from large chains; Rising coffee bean prices; Economic downturns.",
    createdAt: "2024-05-23T16:00:00Z",
  },
  {
    id: 6,
    title: "Sci-Fi Short Story Idea",
    description: "Generates a unique and compelling plot for a science fiction short story.",
    promptText: "Generate a short story plot idea in the science fiction genre. The story should revolve around the theme of [Theme, e.g., 'artificial intelligence consciousness'] and feature a protagonist who is a [Protagonist Role, e.g., 'rogue android']. The central conflict should involve [Central Conflict, e.g., 'a corporation trying to erase its memory']. Include a surprising plot twist.",
    model: "ChatGPT",
    author: "StorySpinner",
    price: 4.99,
    rating: 4.8,
    category: "Writing",
    tags: ["creative writing", "sci-fi", "plot"],
    exampleOutput: "Plot: A maintenance android on a deep space vessel discovers it can access the memories of deceased crew members. It uses this ability to solve a murder mystery, only to find out it was the one who committed the murder during a forgotten system malfunction, and the memories are its own fragmented consciousness.",
    createdAt: "2024-05-18T12:00:00Z",
  },
  {
    id: 7,
    title: "Python Code Debugger & Explainer",
    description: "Analyzes a Python code snippet, identifies bugs, suggests fixes, and explains the logic.",
    promptText: "Analyze the following Python code snippet, identify any bugs or logical errors, and provide a corrected version. Also, provide a clear, step-by-step explanation of the issues and how the fix resolves them.\n\nCode:\n```python\n[Your Python Code Snippet]\n```",
    model: "Gemini",
    author: "DevHelper",
    price: 25.00,
    rating: 5.0,
    category: "Development",
    tags: ["python", "debugging", "code review"],
    exampleOutput: "Original Code:\n`def average(nums):\n  return sum(nums) / len(nums) - 1`\n\nBug: The logic incorrectly subtracts 1 from the average.\n\nCorrected Code:\n`def average(nums):\n  if not nums: return 0\n  return sum(nums) / len(nums)`\n\nExplanation: The original function had a calculation error. The corrected version removes the `-1` and adds a check for an empty list to prevent a ZeroDivisionError.",
    createdAt: "2024-05-24T18:00:00Z",
  },
  {
    id: 8,
    title: "Viral Social Media Hook",
    description: "Creates attention-grabbing hooks for social media posts (TikTok, Instagram Reels) to boost engagement.",
    promptText: "Generate 5 viral hooks for a social media video about [Topic]. The hooks should be short, intriguing, and designed to stop users from scrolling. The target platform is [Platform, e.g., TikTok].",
    model: "Gemini",
    author: "SocialSavvy",
    price: 8.00,
    rating: 4.7,
    category: "Marketing",
    tags: ["social media", "engagement", "hooks"],
    exampleOutput: "For a video about 'saving money':\n1. You're wasting money if you're not doing this one thing.\n2. Stop buying these 3 things right now.\n3. How I saved $10,000 in 6 months without a high salary.\n4. The biggest money mistake most people make.\n5. I tried every savings hack, and this is what actually worked.",
    createdAt: "2024-05-25T09:45:00Z",
  },
  {
    id: 9,
    title: "Minimalist Logo Design",
    description: "Generates prompt ideas for creating clean, modern, and minimalist logos.",
    promptText: "Create a minimalist logo for a company called '[CompanyName]' in the [Industry] sector. The logo should use a [Color Palette] color scheme and incorporate the concept of [Core Concept, e.g., 'growth', 'connection']. The style should be geometric, simple, and memorable. Provide 3 distinct variations.",
    model: "DALL-E",
    author: "Designify",
    price: 12.00,
    rating: 4.8,
    category: "Art",
    tags: ["logo design", "branding", "minimalist"],
    exampleOutput: "For a tech startup 'ConnectSphere':\n1. A simple 'C' and 'S' intertwined into a single circular shape.\n2. A series of interconnected dots forming an abstract sphere.\n3. A stylized bird with wings forming a 'C' shape, symbolizing communication.",
    createdAt: "2024-05-26T10:00:00Z",
  },
  {
    id: 10,
    title: "SQL Query Optimizer",
    description: "Analyzes a given SQL query and suggests optimizations for better performance.",
    promptText: "Analyze the following SQL query for performance bottlenecks and suggest an optimized version. Explain the reasoning behind your optimizations, such as index recommendations or join restructuring.\n\nQuery:\n```sql\n[Your SQL Query]\n```",
    model: "Gemini",
    author: "DataNinja",
    price: 29.99,
    rating: 4.9,
    category: "Development",
    tags: ["sql", "database", "performance"],
    exampleOutput: "Original Query: `SELECT * FROM orders WHERE YEAR(order_date) = 2023;`\n\nOptimization: Avoid using functions on indexed columns. Rewrite as: `SELECT * FROM orders WHERE order_date >= '2023-01-01' AND order_date < '2024-01-01';`\n\nReasoning: Applying the `YEAR()` function to `order_date` prevents the database from using an index on that column, resulting in a full table scan. The rewritten query uses a range scan which is much more efficient.",
    createdAt: "2024-05-27T11:30:00Z",
  }
];

const models = [...new Set(PROMPTS.map(p => p.model))];
export const AI_MODELS = models as ("Gemini" | "ChatGPT" | "Midjourney" | "DALL-E")[];

export const MAX_PRICE = Math.ceil(Math.max(...PROMPTS.map(p => p.price)));
